@startuml VegEvery
' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho


entity "users" as users {
  *id
  --
  name
  password
  secret_question
  answer_to_secret_question
  vegetarian_type
  icon
  created_at
  updated_at
}

' entity "user_common_settings" as user_common_settings {
'   *id
'   --
'   user_id
'   vegetarian_type
'   icon
'   created_at
'   updated_at
' }

entity "articles_of_recipe" as articles_of_recipe {
  *id
  --
  user_id (FK)
  material_id (FK)
  title
  thumbnail
  cooking_time
  number_of_likes
  servings
  vegan
  oriental
  ovo
  pesca
  lacto
  pollo
  fruitarian
  created_at
  updated_at
}

entity "recepi_steps" as recepi_steps {
  *id
  --
  article_of_recipe_id (FK)
  order
  image
  text
  created_at
  updated_at
}

entity "materials" as materials {
  *id
  --
  article_of_recipe_id (FK)
  name
  quantity
  unit
  created_at
  updated_at
}

entity "articles_of_item" as articles_of_item {
  *id
  --
  user_id (FK)
  title
  thumbnail
  number_of_likes
  vegan
  oriental
  ovo
  pesca
  lacto
  pollo
  fruitarian
  created_at
  updated_at
}

entity "items" as items {
  *id
  --
  article_of_item_id (FK)
  name
  where_to_buy
  price
  created_at
  updated_at
}

entity "reports" as reports {
  *id
  --
  article_of_item_id (FK)
  order
  image
  text
  created_at
  updated_at
}

entity "comments_to_recipe" as comments_to_recipe {
  *id
  --
  article_of_recipe_id (FK)
  user_id (FK)
  text
  number_of_likes
  created_at
  updated_at
}

entity "comments_to_item" as comments_to_item {
  *id
  --
  article_of_item_id (FK)
  user_id (FK)
  text
  number_of_likes
  created_at
  updated_at
}

entity "tags" as tags {
  *id
  --
  name
  created_at
  updated_at
}

entity "article_of_recipe_tag" as article_of_recipe_tag {
  *article_of_recipe_id (FK)
  *tag_id (FK)
  --
  created_at
  updated_at
}

entity "article_of_item_tag" as article_of_item_tag {
  *article_of_item_id (FK)
  *tag_id (FK)
  --
  created_at
  updated_at
}

entity "reviews" as reviews {
  *id
  --
  user_id (FK)
  display_name
  thumbnail
  star
  text
  vegan
  oriental
  ovo
  pesca
  lacto
  pollo
  fruitarian
  created_at
  updated_at
}

entity "menus" as menus {
  *id
  --
  review_id
  name
  price
  created_at
  updated_at
}

entity "bookshelves" as bookshelves {
  *id
  --
  user_id (FK)
  name
  created_at
  updated_at
}

entity "favorites" as favorites {
  *bookshelf_id (FK)
  *article_type
  *article_id
  --
  created_at
  updated_at
}

users ||--o{ articles_of_recipe
articles_of_recipe ||--|{ recepi_steps
articles_of_recipe ||-l-|{ materials
articles_of_recipe ||-d-o{ article_of_recipe_tag
tags ||-u-o{ article_of_recipe_tag
articles_of_recipe ||-u-o{ comments_to_recipe
users ||-u-o{ comments_to_recipe
users ||-d-o{articles_of_item
articles_of_item ||--o{ article_of_item_tag
tags ||--o{ article_of_item_tag
articles_of_item ||--o{ comments_to_item
articles_of_item ||-l-o{ items
articles_of_item ||-d-o{ reports
users ||-r-o{ comments_to_item
users ||-u-o{bookshelves
bookshelves ||-r-o{favorites
articles_of_recipe ||--o{favorites
articles_of_item ||--o{favorites
users ||-l-o{reviews
menus }o--|| reviews
@enduml
