@startuml VegEvery
' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho


entity "users" as users {
  *id
  --
  name
  password
  secret_question
  answer_to_secret_question
  vegetarian_type
  icon_url
  icon_path
  created_at
  updated_at
}

entity "personal_access_tokens" as personal_access_tokens {
  *id
  --
  tokenable
  name
  token
  abilities
  last_used_at
  expires_at
  created_at
  updated_at
}

entity "social_accounts" as social_accounts {
  *id
  --
  user_id (FK)
  provider_id
  provider
  created_at
  updated_at
}

entity "articles_of_recipe" as articles_of_recipe {
  *id
  --
  user_id (FK)
  title
  thumbnail_path
  thumbnail_url
  cooking_time
  number_of_likes
  servings
  vegan
  oriental_vegetarian
  ovo_vegetarian
  pescatarian
  lacto_vegetarian
  pollo_vegetarian
  fruitarian
  other_vegetarian
  created_at
  updated_at
}

entity "recepi_steps" as recepi_steps {
  *id
  --
  article_of_recipe_id (FK)
  order
  image_path
  image_url
  text
  created_at
  updated_at
}

entity "materials" as materials {
  *id
  --
  article_of_recipe_id (FK)
  name
  quantity
  unit
  created_at
  updated_at
}

entity "articles_of_item" as articles_of_item {
  *id
  --
  user_id (FK)
  title
  thumbnail_path
  thumbnail_url
  number_of_likes
  vegan
  oriental_vegetarian
  ovo_vegetarian
  pescatarian
  lacto_vegetarian
  pollo_vegetarian
  fruitarian
  other_vegetarian
  created_at
  updated_at
}

entity "items" as items {
  *id
  --
  article_of_item_id (FK)
  name
  where_to_buy
  price
  created_at
  updated_at
}

entity "reports" as reports {
  *id
  --
  article_of_item_id (FK)
  order
  image_path
  image_url
  text
  created_at
  updated_at
}

entity "comments_to_recipe" as comments_to_recipe {
  *id
  --
  article_of_recipe_id (FK)
  user_id (FK)
  text
  number_of_likes
  created_at
  updated_at
}

entity "comments_to_item" as comments_to_item {
  *id
  --
  article_of_item_id (FK)
  user_id (FK)
  text
  number_of_likes
  created_at
  updated_at
}

entity "tags" as tags {
  *id
  --
  name
  created_at
  updated_at
}

entity "article_of_recipe_tag" as article_of_recipe_tag {
  *id
  *article_of_recipe_id (FK)
  *tag_id (FK)
  --
  created_at
  updated_at
}

entity "article_of_item_tag" as article_of_item_tag {
  *id
  *article_of_item_id (FK)
  *tag_id (FK)
  --
  created_at
  updated_at
}

entity "restaurants" as restaurants {
  *id
  --
  name
  place_id
  latitude
  longitude
  star
  vegan
  oriental_vegetarian
  ovo_vegetarian
  pescatarian
  lacto_vegetarian
  pollo_vegetarian
  fruitarian
  other_vegetarian
  created_at
  updated_at
}

entity "reviews" as reviews {
  *id
  --
  user_id (FK)
  restaurant_id (FK)
  thumbnail_path
  thumbnail_url
  star
  text
  number_of_likes
}

entity "menus" as menus {
  *id
  --
  review_id
  name
  price
  vegan
  oriental_vegetarian
  ovo_vegetarian
  pescatarian
  lacto_vegetarian
  pollo_vegetarian
  fruitarian
  other_vegetarian
  created_at
  updated_at
  created_at
  updated_at
}

entity "bookshelves" as bookshelves {
  *id
  --
  user_id (FK)
  name
  created_at
  updated_at
}

entity "bookshelf_article_of_recipe" as bookshelf_article_of_recipe {
  *id
  *bookshelf_id (FK)
  *article_of_recipe (FK)
  --
  created_at
  updated_at
}

entity "bookshelf_article_of_item" as bookshelf_article_of_item {
  *id
  *bookshelf_id (FK)
  *article_of_item (FK)
  --
  created_at
  updated_at
}

entity "likes" as likes {
  *id
  user_id (FK)
  likeable_id
  likeable_type
  --
  created_at
  updated_at
}

entity "images_in_storage" as images_in_storage {
  *id
  --
  path
  fullpath
  url
  created_at
  updated_at
}

users ||--o{ personal_access_tokens
users ||--o{ social_accounts
users ||-r-o{ articles_of_recipe
articles_of_recipe ||-r-|{ recepi_steps
articles_of_recipe ||--|{ materials
articles_of_recipe ||--o{ article_of_recipe_tag
tags ||-r-o{ article_of_recipe_tag
articles_of_recipe ||-l-o{ comments_to_recipe
users ||-r-o{ comments_to_recipe
users ||-l-o{articles_of_item
articles_of_item ||--o{ article_of_item_tag
tags ||-u-o{ article_of_item_tag
articles_of_item ||-u-o{ comments_to_item
articles_of_item ||-u-o{ items
articles_of_item ||-l-o{ reports
users ||-l-o{ comments_to_item
users ||-d-o{bookshelves
bookshelves ||-r-|{bookshelf_article_of_recipe
articles_of_recipe ||--o{bookshelf_article_of_recipe
bookshelves ||--|{bookshelf_article_of_item
articles_of_item ||--o{bookshelf_article_of_item
users ||-u-o{reviews
menus }o--|| reviews
restaurants ||-l-|{ reviews
users |o-l-|{ likes
likes |o-r-|{ articles_of_recipe
likes |o-r-|{ articles_of_item
images_in_storage ||--|| articles_of_recipe
images_in_storage||--|| articles_of_item
images_in_storage |o-r-|| recepi_steps
images_in_storage|o--|| reports

@enduml
